name: Generate pacman animation

on:
  schedule:
    - cron: "0 0 * * *"  # Runs once daily at midnight UTC
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-24.04
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@v5.0.0
        with:
          github_user_name: ${{ github.repository_owner }}

      - name: Push pacman-contribution-graph.svg to output branch
        uses: crazy-max/ghaction-github-pages@v5
        with:
          target_branch: output
          build_dir: dist
          commit_message: "chore: update pacman-contribution-graph.svg"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
